version: "2"
checks:
  similar-code:
    enabled: true
    config:
      threshold: 90
exclude_patterns:
  - "**/wwwroot/lib/"
  - "**/wwwroot/js/signalr/"
  - "**/wwwroot/js/FlowR.js"
  - "docs/"
  - "docfx/"
  - "FlowR.Tests/*.feature.cs"