environment:
  access_token:
    secure: 3863e27f8bb5f7ccaff7a8c9163cea054a52caed
  op_build_user: "abbadon1334"
  op_build_user_email: "fdanti@gmail.com"

image: Visual Studio 2019
before_build:
  - choco install docfx -y

build_script:
  - dotnet build ./FlowR.sln

on_success:
  - docfx FlowR.DocFx/docfx.json
  - git config --global core.autocrlf false
  - git config --global credential.helper store
  - ps : Set-Content -Path "$HOME\.git-credentials" -Value "https://$($env:access_token):x-oauth-basic@github.com`n" -NoNewline
  - git config --global user.email $env:op_build_user_email
  - git config --global user.name $env:op_build_user
  - git clone https://github.com/abbadon1334/RealFlowR.git --branch gh-pages tmp_docs
  - cd tmp_docs
  - git rm -r *
  - cp -r ../docs/* .
  - git add . -A
  - git commit -m "Update generated documentation"
  - git push origin gh-pages