### YamlMime:ManagedReference
items:
- uid: FlowR.Core.ApplicationTimers
  commentId: T:FlowR.Core.ApplicationTimers
  id: ApplicationTimers
  parent: FlowR.Core
  children:
  - FlowR.Core.ApplicationTimers.Add(FlowR.Core.ApplicationTimer)
  - FlowR.Core.ApplicationTimers.AddTimer(System.Int32,System.EventHandler,System.Boolean)
  - FlowR.Core.ApplicationTimers.Remove(FlowR.Core.ApplicationTimer)
  langs:
  - csharp
  - vb
  name: ApplicationTimers
  nameWithType: ApplicationTimers
  fullName: FlowR.Core.ApplicationTimers
  type: Class
  source:
    remote:
      path: FlowR.Core/ApplicationTimers.cs
      branch: master
      repo: https://github.com/abbadon1334/RealFlowR.git
    id: ApplicationTimers
    path: ../FlowR.Core/ApplicationTimers.cs
    startLine: 8
  assemblies:
  - FlowR.Core
  namespace: FlowR.Core
  summary: "\nManage Application Timers\n"
  example: []
  syntax:
    content: public class ApplicationTimers
    content.vb: Public Class ApplicationTimers
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: FlowR.Core.ApplicationTimers.Add(FlowR.Core.ApplicationTimer)
  commentId: M:FlowR.Core.ApplicationTimers.Add(FlowR.Core.ApplicationTimer)
  id: Add(FlowR.Core.ApplicationTimer)
  parent: FlowR.Core.ApplicationTimers
  langs:
  - csharp
  - vb
  name: Add(ApplicationTimer)
  nameWithType: ApplicationTimers.Add(ApplicationTimer)
  fullName: FlowR.Core.ApplicationTimers.Add(FlowR.Core.ApplicationTimer)
  type: Method
  source:
    remote:
      path: FlowR.Core/ApplicationTimers.cs
      branch: master
      repo: https://github.com/abbadon1334/RealFlowR.git
    id: Add
    path: ../FlowR.Core/ApplicationTimers.cs
    startLine: 16
  assemblies:
  - FlowR.Core
  namespace: FlowR.Core
  summary: "\nAdd Timer\n"
  example: []
  syntax:
    content: public void Add(ApplicationTimer timer)
    parameters:
    - id: timer
      type: FlowR.Core.ApplicationTimer
      description: ''
    content.vb: Public Sub Add(timer As ApplicationTimer)
  overload: FlowR.Core.ApplicationTimers.Add*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: FlowR.Core.ApplicationTimers.AddTimer(System.Int32,System.EventHandler,System.Boolean)
  commentId: M:FlowR.Core.ApplicationTimers.AddTimer(System.Int32,System.EventHandler,System.Boolean)
  id: AddTimer(System.Int32,System.EventHandler,System.Boolean)
  parent: FlowR.Core.ApplicationTimers
  langs:
  - csharp
  - vb
  name: AddTimer(Int32, EventHandler, Boolean)
  nameWithType: ApplicationTimers.AddTimer(Int32, EventHandler, Boolean)
  fullName: FlowR.Core.ApplicationTimers.AddTimer(System.Int32, System.EventHandler, System.Boolean)
  type: Method
  source:
    remote:
      path: FlowR.Core/ApplicationTimers.cs
      branch: master
      repo: https://github.com/abbadon1334/RealFlowR.git
    id: AddTimer
    path: ../FlowR.Core/ApplicationTimers.cs
    startLine: 30
  assemblies:
  - FlowR.Core
  namespace: FlowR.Core
  summary: "\nAdd Timer.\n"
  example: []
  syntax:
    content: public void AddTimer(int delay, EventHandler callback, bool infinite = true)
    parameters:
    - id: delay
      type: System.Int32
      description: ''
    - id: callback
      type: System.EventHandler
      description: ''
    - id: infinite
      type: System.Boolean
      description: ''
    content.vb: Public Sub AddTimer(delay As Integer, callback As EventHandler, infinite As Boolean = True)
  overload: FlowR.Core.ApplicationTimers.AddTimer*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: FlowR.Core.ApplicationTimers.Remove(FlowR.Core.ApplicationTimer)
  commentId: M:FlowR.Core.ApplicationTimers.Remove(FlowR.Core.ApplicationTimer)
  id: Remove(FlowR.Core.ApplicationTimer)
  parent: FlowR.Core.ApplicationTimers
  langs:
  - csharp
  - vb
  name: Remove(ApplicationTimer)
  nameWithType: ApplicationTimers.Remove(ApplicationTimer)
  fullName: FlowR.Core.ApplicationTimers.Remove(FlowR.Core.ApplicationTimer)
  type: Method
  source:
    remote:
      path: FlowR.Core/ApplicationTimers.cs
      branch: master
      repo: https://github.com/abbadon1334/RealFlowR.git
    id: Remove
    path: ../FlowR.Core/ApplicationTimers.cs
    startLine: 40
  assemblies:
  - FlowR.Core
  namespace: FlowR.Core
  summary: "\nRemove Timer.\n"
  example: []
  syntax:
    content: public void Remove(ApplicationTimer timer)
    parameters:
    - id: timer
      type: FlowR.Core.ApplicationTimer
      description: ''
    content.vb: Public Sub Remove(timer As ApplicationTimer)
  overload: FlowR.Core.ApplicationTimers.Remove*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: FlowR.Core
  commentId: N:FlowR.Core
  name: FlowR.Core
  nameWithType: FlowR.Core
  fullName: FlowR.Core
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: FlowR.Core.ApplicationTimers.Add*
  commentId: Overload:FlowR.Core.ApplicationTimers.Add
  name: Add
  nameWithType: ApplicationTimers.Add
  fullName: FlowR.Core.ApplicationTimers.Add
- uid: FlowR.Core.ApplicationTimer
  commentId: T:FlowR.Core.ApplicationTimer
  parent: FlowR.Core
  name: ApplicationTimer
  nameWithType: ApplicationTimer
  fullName: FlowR.Core.ApplicationTimer
- uid: FlowR.Core.ApplicationTimers.AddTimer*
  commentId: Overload:FlowR.Core.ApplicationTimers.AddTimer
  name: AddTimer
  nameWithType: ApplicationTimers.AddTimer
  fullName: FlowR.Core.ApplicationTimers.AddTimer
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.EventHandler
  commentId: T:System.EventHandler
  parent: System
  isExternal: true
  name: EventHandler
  nameWithType: EventHandler
  fullName: System.EventHandler
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: FlowR.Core.ApplicationTimers.Remove*
  commentId: Overload:FlowR.Core.ApplicationTimers.Remove
  name: Remove
  nameWithType: ApplicationTimers.Remove
  fullName: FlowR.Core.ApplicationTimers.Remove
