### YamlMime:ManagedReference
items:
- uid: FlowR.Core.ApplicationTimers
  commentId: T:FlowR.Core.ApplicationTimers
  id: ApplicationTimers
  parent: FlowR.Core
  children:
  - FlowR.Core.ApplicationTimers.Add(FlowR.Core.ApplicationTimer)
  - FlowR.Core.ApplicationTimers.AddTimer(System.Int32,EventHandler,System.Boolean)
  - FlowR.Core.ApplicationTimers.Remove(FlowR.Core.ApplicationTimer)
  langs:
  - csharp
  - vb
  name: ApplicationTimers
  nameWithType: ApplicationTimers
  fullName: FlowR.Core.ApplicationTimers
  type: Class
  source:
    remote:
      path: FlowR.Core/ApplicationTimers.cs
      branch: master
      repo: https://github.com/abbadon1334/RealFlowR.git
    id: ApplicationTimers
    path: FlowR.Core/ApplicationTimers.cs
    startLine: 8
  assemblies:
  - FlowR.Core
  namespace: FlowR.Core
  summary: "\nManage Application Timers\n"
  example: []
  syntax:
    content: 'public class ApplicationTimers : object'
    content.vb: >-
      Public Class ApplicationTimers

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: FlowR.Core.ApplicationTimers.Add(FlowR.Core.ApplicationTimer)
  commentId: M:FlowR.Core.ApplicationTimers.Add(FlowR.Core.ApplicationTimer)
  id: Add(FlowR.Core.ApplicationTimer)
  parent: FlowR.Core.ApplicationTimers
  langs:
  - csharp
  - vb
  name: Add(ApplicationTimer)
  nameWithType: ApplicationTimers.Add(ApplicationTimer)
  fullName: FlowR.Core.ApplicationTimers.Add(FlowR.Core.ApplicationTimer)
  type: Method
  source:
    remote:
      path: FlowR.Core/ApplicationTimers.cs
      branch: master
      repo: https://github.com/abbadon1334/RealFlowR.git
    id: Add
    path: FlowR.Core/ApplicationTimers.cs
    startLine: 16
  assemblies:
  - FlowR.Core
  namespace: FlowR.Core
  summary: "\nAdd Timer\n"
  example: []
  syntax:
    content: public void Add(ApplicationTimer timer)
    parameters:
    - id: timer
      type: FlowR.Core.ApplicationTimer
      description: ''
    content.vb: Public Sub Add(timer As ApplicationTimer)
  overload: FlowR.Core.ApplicationTimers.Add*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: FlowR.Core.ApplicationTimers.AddTimer(System.Int32,EventHandler,System.Boolean)
  commentId: M:FlowR.Core.ApplicationTimers.AddTimer(System.Int32,EventHandler,System.Boolean)
  id: AddTimer(System.Int32,EventHandler,System.Boolean)
  parent: FlowR.Core.ApplicationTimers
  langs:
  - csharp
  - vb
  name: AddTimer(Int32, EventHandler, Boolean)
  nameWithType: ApplicationTimers.AddTimer(Int32, EventHandler, Boolean)
  fullName: FlowR.Core.ApplicationTimers.AddTimer(System.Int32, EventHandler, System.Boolean)
  type: Method
  source:
    remote:
      path: FlowR.Core/ApplicationTimers.cs
      branch: master
      repo: https://github.com/abbadon1334/RealFlowR.git
    id: AddTimer
    path: FlowR.Core/ApplicationTimers.cs
    startLine: 30
  assemblies:
  - FlowR.Core
  namespace: FlowR.Core
  summary: "\nAdd Timer.\n"
  example: []
  syntax:
    content: public void AddTimer(int delay, EventHandler callback, bool infinite = true)
    parameters:
    - id: delay
      type: System.Int32
      description: ''
    - id: callback
      type: EventHandler
      description: ''
    - id: infinite
      type: System.Boolean
      description: ''
    content.vb: Public Sub AddTimer(delay As Integer, callback As EventHandler, infinite As Boolean = True)
  overload: FlowR.Core.ApplicationTimers.AddTimer*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: FlowR.Core.ApplicationTimers.Remove(FlowR.Core.ApplicationTimer)
  commentId: M:FlowR.Core.ApplicationTimers.Remove(FlowR.Core.ApplicationTimer)
  id: Remove(FlowR.Core.ApplicationTimer)
  parent: FlowR.Core.ApplicationTimers
  langs:
  - csharp
  - vb
  name: Remove(ApplicationTimer)
  nameWithType: ApplicationTimers.Remove(ApplicationTimer)
  fullName: FlowR.Core.ApplicationTimers.Remove(FlowR.Core.ApplicationTimer)
  type: Method
  source:
    remote:
      path: FlowR.Core/ApplicationTimers.cs
      branch: master
      repo: https://github.com/abbadon1334/RealFlowR.git
    id: Remove
    path: FlowR.Core/ApplicationTimers.cs
    startLine: 40
  assemblies:
  - FlowR.Core
  namespace: FlowR.Core
  summary: "\nRemove Timer.\n"
  example: []
  syntax:
    content: public void Remove(ApplicationTimer timer)
    parameters:
    - id: timer
      type: FlowR.Core.ApplicationTimer
      description: ''
    content.vb: Public Sub Remove(timer As ApplicationTimer)
  overload: FlowR.Core.ApplicationTimers.Remove*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: FlowR.Core
  commentId: N:FlowR.Core
  name: FlowR.Core
  nameWithType: FlowR.Core
  fullName: FlowR.Core
- uid: FlowR.Core.ApplicationTimers.Add*
  commentId: Overload:FlowR.Core.ApplicationTimers.Add
  name: Add
  nameWithType: ApplicationTimers.Add
  fullName: FlowR.Core.ApplicationTimers.Add
- uid: FlowR.Core.ApplicationTimer
  commentId: T:FlowR.Core.ApplicationTimer
  parent: FlowR.Core
  name: ApplicationTimer
  nameWithType: ApplicationTimer
  fullName: FlowR.Core.ApplicationTimer
- uid: FlowR.Core.ApplicationTimers.AddTimer*
  commentId: Overload:FlowR.Core.ApplicationTimers.AddTimer
  name: AddTimer
  nameWithType: ApplicationTimers.AddTimer
  fullName: FlowR.Core.ApplicationTimers.AddTimer
- uid: System.Int32
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: EventHandler
  isExternal: true
  name: EventHandler
  nameWithType: EventHandler
  fullName: EventHandler
- uid: System.Boolean
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: FlowR.Core.ApplicationTimers.Remove*
  commentId: Overload:FlowR.Core.ApplicationTimers.Remove
  name: Remove
  nameWithType: ApplicationTimers.Remove
  fullName: FlowR.Core.ApplicationTimers.Remove
