### YamlMime:ManagedReference
items:
- uid: FlowR.Core.ApplicationTimer
  commentId: T:FlowR.Core.ApplicationTimer
  id: ApplicationTimer
  parent: FlowR.Core
  children:
  - FlowR.Core.ApplicationTimer.#ctor(System.Int32,EventHandler,System.Boolean)
  - FlowR.Core.ApplicationTimer.OnStop
  - FlowR.Core.ApplicationTimer.Start
  - FlowR.Core.ApplicationTimer.Stop
  langs:
  - csharp
  - vb
  name: ApplicationTimer
  nameWithType: ApplicationTimer
  fullName: FlowR.Core.ApplicationTimer
  type: Class
  source:
    remote:
      path: FlowR.Core/ApplicationTimer.cs
      branch: master
      repo: https://github.com/abbadon1334/RealFlowR.git
    id: ApplicationTimer
    path: FlowR.Core/ApplicationTimer.cs
    startLine: 8
  assemblies:
  - FlowR.Core
  namespace: FlowR.Core
  summary: "\nApplication timer class.\n"
  example: []
  syntax:
    content: 'public class ApplicationTimer : object'
    content.vb: >-
      Public Class ApplicationTimer

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: FlowR.Core.ApplicationTimer.#ctor(System.Int32,EventHandler,System.Boolean)
  commentId: M:FlowR.Core.ApplicationTimer.#ctor(System.Int32,EventHandler,System.Boolean)
  id: '#ctor(System.Int32,EventHandler,System.Boolean)'
  parent: FlowR.Core.ApplicationTimer
  langs:
  - csharp
  - vb
  name: ApplicationTimer(Int32, EventHandler, Boolean)
  nameWithType: ApplicationTimer.ApplicationTimer(Int32, EventHandler, Boolean)
  fullName: FlowR.Core.ApplicationTimer.ApplicationTimer(System.Int32, EventHandler, System.Boolean)
  type: Constructor
  source:
    remote:
      path: FlowR.Core/ApplicationTimer.cs
      branch: master
      repo: https://github.com/abbadon1334/RealFlowR.git
    id: .ctor
    path: FlowR.Core/ApplicationTimer.cs
    startLine: 21
  assemblies:
  - FlowR.Core
  namespace: FlowR.Core
  summary: "\nApplicationTimer\n"
  example: []
  syntax:
    content: public ApplicationTimer(int delay, EventHandler callback, bool infinite = false)
    parameters:
    - id: delay
      type: System.Int32
      description: timeout to trigger Callback
    - id: callback
      type: EventHandler
      description: Callback to be triggered
    - id: infinite
      type: System.Boolean
      description: Timeout = false, Interval = true
    content.vb: Public Sub New(delay As Integer, callback As EventHandler, infinite As Boolean = False)
  overload: FlowR.Core.ApplicationTimer.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: FlowR.Core.ApplicationTimer.Start
  commentId: M:FlowR.Core.ApplicationTimer.Start
  id: Start
  parent: FlowR.Core.ApplicationTimer
  langs:
  - csharp
  - vb
  name: Start()
  nameWithType: ApplicationTimer.Start()
  fullName: FlowR.Core.ApplicationTimer.Start()
  type: Method
  source:
    remote:
      path: FlowR.Core/ApplicationTimer.cs
      branch: master
      repo: https://github.com/abbadon1334/RealFlowR.git
    id: Start
    path: FlowR.Core/ApplicationTimer.cs
    startLine: 31
  assemblies:
  - FlowR.Core
  namespace: FlowR.Core
  summary: "\nStart the Timer.\n"
  example: []
  syntax:
    content: public void Start()
    content.vb: Public Sub Start
  overload: FlowR.Core.ApplicationTimer.Start*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: FlowR.Core.ApplicationTimer.Stop
  commentId: M:FlowR.Core.ApplicationTimer.Stop
  id: Stop
  parent: FlowR.Core.ApplicationTimer
  langs:
  - csharp
  - vb
  name: Stop()
  nameWithType: ApplicationTimer.Stop()
  fullName: FlowR.Core.ApplicationTimer.Stop()
  type: Method
  source:
    remote:
      path: FlowR.Core/ApplicationTimer.cs
      branch: master
      repo: https://github.com/abbadon1334/RealFlowR.git
    id: Stop
    path: FlowR.Core/ApplicationTimer.cs
    startLine: 47
  assemblies:
  - FlowR.Core
  namespace: FlowR.Core
  summary: "\nStop the Timer\n"
  example: []
  syntax:
    content: public void Stop()
    content.vb: Public Sub Stop
  overload: FlowR.Core.ApplicationTimer.Stop*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: FlowR.Core.ApplicationTimer.OnStop
  commentId: E:FlowR.Core.ApplicationTimer.OnStop
  id: OnStop
  parent: FlowR.Core.ApplicationTimer
  langs:
  - csharp
  - vb
  name: OnStop
  nameWithType: ApplicationTimer.OnStop
  fullName: FlowR.Core.ApplicationTimer.OnStop
  type: Event
  source:
    remote:
      path: FlowR.Core/ApplicationTimer.cs
      branch: master
      repo: https://github.com/abbadon1334/RealFlowR.git
    id: OnStop
    path: FlowR.Core/ApplicationTimer.cs
    startLine: 56
  assemblies:
  - FlowR.Core
  namespace: FlowR.Core
  summary: "\nEvent handler for stop event.\n"
  example: []
  syntax:
    content: public event EventHandler OnStop
    return:
      type: EventHandler
    content.vb: Public Event OnStop As EventHandler
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: FlowR.Core
  commentId: N:FlowR.Core
  name: FlowR.Core
  nameWithType: FlowR.Core
  fullName: FlowR.Core
- uid: FlowR.Core.ApplicationTimer.#ctor*
  commentId: Overload:FlowR.Core.ApplicationTimer.#ctor
  name: ApplicationTimer
  nameWithType: ApplicationTimer.ApplicationTimer
  fullName: FlowR.Core.ApplicationTimer.ApplicationTimer
- uid: System.Int32
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: EventHandler
  isExternal: true
  name: EventHandler
  nameWithType: EventHandler
  fullName: EventHandler
- uid: System.Boolean
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: FlowR.Core.ApplicationTimer.Start*
  commentId: Overload:FlowR.Core.ApplicationTimer.Start
  name: Start
  nameWithType: ApplicationTimer.Start
  fullName: FlowR.Core.ApplicationTimer.Start
- uid: FlowR.Core.ApplicationTimer.Stop*
  commentId: Overload:FlowR.Core.ApplicationTimer.Stop
  name: Stop
  nameWithType: ApplicationTimer.Stop
  fullName: FlowR.Core.ApplicationTimer.Stop
