# This is a basic workflow to help you get started with Actions

name: DocGeneration

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    
jobs:
  generate-docs:
    runs-on: windows-latest
    name: Generate Docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Generate Documentation
        uses: FuLagann/csharp-docs-generator@master
        with:
          build-tasks: dotnet build
          cleanup-tasks: dotnet clean
          output-path: docs/api
          user-email: fdanti@gmail.com
          user-name: C# Document Generator
